version: '4'

networks:
  eventify-network:
    name: eventify-network
    driver: bridge

services:

  db:
    image: postgres:14.6  # Use an official PostgreSQL image from Docker Hub
    networks:
     - eventify-network
    environment:
      POSTGRES_DB: eventify
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    healthcheck:
        test: pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER} || exit 1
        interval: 5s
        timeout: 5s
        retries: 5

  web:
    networks:
     - eventify-network
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .docker-env
    depends_on:
      db:
        condition: service_healthy
