version: '4'

networks:
  eventify-network:
    name: eventify-network
    driver: bridge

services:

  db:
    image: postgres:14.6  # Use an official PostgreSQL image from Docker Hub
    networks:
     - eventify-network
    volumes:
     - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: eventify
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    healthcheck:
        test: pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER} || exit 1
        interval: 5s
        timeout: 5s
        retries: 5

  app:
    networks:
     - eventify-network
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .docker-env
    depends_on:
      db:
        condition: service_healthy

  nginx:
    build: ./nginx
    networks:
      - eventify-network
    volumes:
      - static:/app/static
    ports:
      - "80:80"
    depends_on:
      - app


volumes:
  postgres_data:
  static:
